---
title: "Gender equality in labour market doc"
author: "moi"
date: "27/10/2019"
output:
  word_document: default
  html_document: default
---

```{r, include=FALSE}
# Downloading require packages 
#install.packages('eurostat')
#install.packages('survival')
library(eurostat)
library(dplyr)
library(tidyverse)
library(tidyr)
library(ggplot2)
library(lubridate)
library(car)
library(RMySQL)
library(survival)
library(mapproj)
library(mosaic)
library(scales)
```

```{r}
# Downloading and naming the data frame from eurostat
doc1 <- get_eurostat(id= "lfsi_emp_a", time_format = "date", filters = "none", type = "code", cache = TRUE)
doc2 <- get_eurostat(id= "lfsa_ergaed", time_format = "date", filters = "none", type = "code", cache = TRUE)
doc3 <- get_eurostat(id= "lfsa_eppgan", time_format = "date", filters = "none", type = "code", cache = TRUE)
doc4 <- get_eurostat(id= "lfsa_etgar", time_format = "date", filters = "none", type = "code", cache = TRUE)
doc5 <- get_eurostat(id= "une_rt_a", time_format = "date", filters = "none", type = "code", cache = TRUE)
doc6 <- get_eurostat(id= "une_ltu_a", time_format = "date", filters = "none", type = "code", cache = TRUE)
doc7<- get_eurostat(id= "demo_gind", time_format = "date", filters = "none", type = "code", cache = TRUE)
doc8<- get_eurostat(id= "nama_10_gdp", time_format = "date", filters = "none", type = "code", cache = TRUE)
doc9<- get_eurostat(id= "earn_gr_gpgr2", time_format = "date", filters = "none",
type = "code", cache = TRUE)   
```

```{r}
# Check if there are missing values
any(is.na(doc1))
any(is.na(doc2))
any(is.na(doc3))
any(is.na(doc4))
any(is.na(doc5))
any(is.na(doc6))
any(is.na(doc7))
any(is.na(doc8))
any(is.na(doc9))
```

```{r}
# Remove NA
doc2=na.omit(doc2)
doc3=na.omit(doc3)
doc4=na.omit(doc4)
doc6=na.omit(doc6)
doc7=na.omit(doc7)
doc8=na.omit(doc8)
doc9=na.omit(doc9)
```

```{r}
# Check if the missing value are gone
sum(is.na(doc2)) 
sum(is.na(doc3)) 
sum(is.na(doc4)) 
sum(is.na(doc6)) 
sum(is.na(doc7)) 
sum(is.na(doc8)) 
sum(is.na(doc9)) 
```


```{r}
# date format
doc1$time <- format(doc1$time, "%Y")
doc2$time <- format(doc2$time, "%Y")
doc3$time <- format(doc3$time, "%Y")
doc4$time <- format(doc4$time, "%Y")
doc5$time <- format(doc5$time, "%Y")
doc6$time <- format(doc6$time, "%Y")
doc7$time <- format(doc7$time, "%Y")
doc9$time <- format(doc9$time, "%Y")
```

```{r}
# only the doc8 is not as date so we change it in date format before
class(doc8$time)
doc8$time=as.Date(doc8$time,"%Y-%m-%d")
doc8$time <- format(doc8$time,"%Y")
```

```{r}
# filter to keep data from 2006 
doc1=doc1 %>% filter(time>=2006)
doc2=doc2 %>% filter(time>=2006)
doc3=doc3 %>% filter(time>=2006)
doc4=doc4 %>%filter(time>=2006)
# doc5=doc5 %>%filter(time>=2006)
doc6=doc6 %>%filter(time>=2006)
doc7=doc7 %>% filter(time>=2006)
doc8=doc8 %>% filter(time>=2006)
doc9=doc9 %>% filter(time>=2006)

# filter to keep data from 20-64 year old category
doc1=doc1%>% filter(age== "Y20-64")
doc2=doc2%>% filter(age== "Y20-64")
doc3=doc3%>% filter(age== "Y20-64")
doc4=doc4%>% filter(age== "Y20-64")
doc6=doc6%>% filter(age== "Y20-64")
doc5=doc5%>% filter(age== "TOTAL")

# delete age column
doc1=doc1%>% select(-"age")
doc2=doc2%>% select(-"age")
doc3=doc3%>% select(-"age")
doc4=doc4%>% select(-"age")
doc5=doc5%>% select(-"age")
doc6=doc6%>% select(-"age")

# we keep just PC (pourcentage) unit column
doc1=doc1%>% filter(unit== "PC_POP")
doc1=doc1%>% select(-"unit")
doc2=doc2%>% select(-"unit") # il n'y a que PC
doc3=doc3%>% select(-"unit")
doc9=doc9%>% select(-"unit")
```

```{r}
# Rename columns, rename labels inside columns, suppress useless stuffs and rename documents

              ### Reminder supprimer total partout car ils dérangent quand on fait les graphiques et ils                          peuvent être calculé en additionnant H + F 

## doc 1 : PC_Act
doc1 <- doc1 %>% 
  rename(country=geo, category=indic_em) 
doc1$category <- car::recode(doc1$category,'"ACT"="Actif"')
doc1$category <- car::recode(doc1$category,'"EMP_LFS"="Total_Employment"')
PC_Act <- doc1 %>% 
  filter(category=="Actif") %>% 
  rename(PC_act=values) %>% 
  filter(sex !="T")

## doc 2 : PC_Emp 
doc2 <- doc2 %>% 
  rename(educ_level=isced11, country=geo, PC_emp=values)  %>%
  filter(educ_level !="NRP")
doc2$educ_level <- car::recode(doc2$educ_level,'"ED0-2"="low";"ED3_4"="Inter";"ED5-8"="high"')
PC_Emp <- doc2

## doc 3 : PC_Partime 
PC_Partime <- doc3 %>% 
  rename(country=geo, PC_parttime_onemp=values) %>% 
  select(-"citizen")

## doc 4 : PC_Temp 
doc4 <- doc4 %>% 
  rename(country=geo, PC_emp=unit)  %>% 
  ### Column PC_emp diviser entre employement et part-time employement qu'est ce que ça veut dire ??? doit on garder   que part time ?? Où le % part time est construit par rapport au % employment ? 
  filter(reason !="NRP") 
  ### Filter TOTAL mais que pour la category TEMPORARY parce qu'on se fou de savoir que le total des cinq = 100% ? 
doc4$PC_emp <- car::recode(doc4$PC_emp,'
  "PC_SAL"="employment";"PC_SAL_TEMP"="Temporary"')
doc4$reason <- car::recode(doc4$reason,'
  "INVTMP"="NocoulJob";"WANTTMP"="NowantJob"')
PC_Temp <- doc4

## doc 5 : PC_Unemp 
### pourquoi pas le supprimer ??? on peut calculer % unemp grâce à emp ? 
PC_Unemp <- doc5 %>% 
  rename(country=geo, PC_unemp=unit) %>% 
  filter(PC_unemp !="THS_PER", PC_unemp !="PC_POP") %>% ### def chomage = unemp / pop active
  select(-PC_unemp) %>% 
  rename(PC_unemp=values)

## doc 6 : PC_Ltunemp 
PC_Ltunemp <- doc6 %>% 
  rename(country=geo, PC_unemp=values) %>% 
  filter(unit !="THS_PER") %>% 
  select(-indic_em)

## doc 7 : Pop_evol 
doc7$indic_de <- car::recode(doc7$indic_de,'"JAN"="T";"MJAN"="M";"FJAN"="F"')
doc7 <- doc7  %>%  filter(indic_de %in% c("T","M", "F"))
Pop_evol <- doc7

## doc 8 : GDPandVA 
GDPandVA <- doc8  %>%  
  filter(na_item %in% c("B1GQ","B1G"))  %>%  
  filter(unit == "CP_MEUR")

## doc 9 : PC_Gapaid 
### Voir quoi faire de la colonne nace_r2????
PC_Gapaid <- doc9 %>% 
  rename(country=geo, PC_gap=values)
PC_Gapaid2 <- PC_Gapaid %>% 
  group_by(country, time) %>%
  summarise(mean_gappaid_percountry = mean(PC_gap))

```

```{r}
# Merge table 
#dataframe <- inner_join(PC_Emp, PC_Partime, by = c("time", "country", "sex"))
### PROBLEM PCPARTIMEEMP x4-5 les mêmes valeurs
```

```{r}
# Rename label country (quand tous les tableaux seront mergé)
```

```{r}
# view relation between two variables
plot(PC_Act$sex, PC_Act$PC_act) 
plot(PC_Act$country, PC_Act$PC_act) 
```
spread(data, bare name of column containing keys, bare name of column containing values) : long to wide
separate(data set, name of the column to split into two, c(“variable1”, “variable2”), sep =”…” ): to separate into two columns

data_frameZ <- data_frameX %>%
      inner_join(data_frameY, by = c("variable1","variable2"))

# histogram of a single variable
hist() 


```{r}
# Cartogram mean gap paid by gender between european countries in 2017
 
datacart <- get_eurostat(id= "earn_gr_gpgr2", time_format = "date", filters = "none",
type = "code", cache = TRUE) %>% 
  filter(time == "2017-01-01") %>%
  group_by(geo) %>%
  summarise(mean_gappaid_percountry = mean(values)) %>%
  mutate(cat = cut_to_classes(mean_gappaid_percountry, n=7, decimals=1))
 
geocart <- get_eurostat_geospatial(resolution = "60", output_class = "df")
 
mapdata <- datacart %>%
  inner_join(geocart, by = "geo")
 
head(select(mapdata,geo,mean_gappaid_percountry,cat,long,lat,order,id))
 
ggplot(mapdata, aes(x = long, y = lat, group = group))+
  geom_polygon(aes(fill=cat), color="grey", size = .1)+ scale_fill_brewer(palette = "YlOrRd") +
  labs(title="Gap paid between men and women throughout Europe, 2017",
       subtitle="Avg. gap paid per country",
       fill="Gap paid (%)") + theme_light()+
  coord_map(xlim=c(-40,40), ylim=c(25,73))



# filter PC_Gapaid2 for work on max min medium
PC_Gapaid22017=PC_Gapaid2%>% filter(time=="2017")

# Country with the lowest gender paid gap
minGP2017=min(PC_Gapaid22017$mean_gappaid_percountry)
mincountGP=PC_Gapaid22017 %>% filter(mean_gappaid_percountry==minGP2017)%>%select(country)
mincountGP # RO, Roumania # 4.73% ( puis Marlte Belgique)

# Country with the hogher gender paid gap
maxGP2017=max(PC_Gapaid22017$mean_gappaid_percountry)
maxcountGP=PC_Gapaid22017 %>% filter(mean_gappaid_percountry==maxGP2017)%>%select(country)
maxcountGP # EE,Estonia # 20%, Republique Tcheque Autriche 

# Country with the mean gender paid gap
MeancountGP=PC_Gapaid22017%>%filter(country=="EU28")
MeancountGP # 16%

```


```{r}
# ACTIVITY RATE

#graph 5 , Quel pays  à le plus faible taux d’activité des femmes (pour connaitre le nombre de femme au foyer ou les femmes découragées)
# Pour l’année 2018, graph avec tous les pays en couleur  pour savoir le quel à le plus faible taux d’activité des femmes


# Graph 28 states europe actif population (woman, man, total, evolution over y)

PC_GapFem= PC_Act %>% filter(sex=="F")
PC_GapFem=PC_GapFem %>% rename(f_act= PC_act) 
PC_GapFem=PC_GapFem%>%  select(f_act,time,country)
PC_GapMal= PC_Act %>% filter(sex=="M")
PC_GapMal=PC_GapMal%>%rename(m_act= PC_act) %>% select(m_act,time,country)
PC_ActGap=left_join(PC_GapFem,PC_GapMal,by=c('time','country'))

PC_ActGap$gap=PC_ActGap$m_act-PC_ActGap$f_act

PC_Act %>% 
  filter(country =="EU28") %>% group_by(sex)%>% ggplot(.,) +
  geom_line(aes(x=time,y=PC_act,colour=sex,group=sex),size=1) +  labs(title="Evolution of Activity   Rate between wooman & men ") + xlab("time") + ylab("activity rate")+ ylim(40,90)+theme(axis.text.x = element_text(angle=38))


# Evolution of activity rate in UE of 28
PC_Act %>% 
  filter(country =="EU28") %>% group_by(sex)%>% ggplot(.,) +
  geom_line(aes(x=time,y=PC_act,colour=sex,group=sex),size=0.5) + labs(title="Evolution of Activity   Rate between wooman & men ") + xlab("time") + ylab("activity rate")+ ylim(40,90)


# Data of women activity rate in 2018

#test gap
PC_ActGapTime=PC_ActGap
PC_ActGap=PC_ActGap %>% 
  filter(! country %in% c("EA17","EA18","EA19","EU15","EU28"))%>% 
  select(- f_act,m_act)%>%filter(time=="2018")

PC_ActGap <- PC_ActGap %>% 
  rename(CNTR_CODE=country) 

PC_ActGap$class=cut_to_classes(PC_ActGap$gap, n=10, style="equal", decimals=1)
geodata <- get_eurostat_geospatial(resolution = "60", nuts_level = "2", year = 2016)
map_data <- inner_join(geodata, PC_ActGap)

  
  ggplot(data=map_data) + geom_sf(aes(fill=class),color="dim grey",size=0.1)+
    scale_fill_brewer(palette = "RdBu") +
    guides(fill = guide_legend(reverse=T, title = "euro")) +
    labs(title="Gender Gap of Activity rate in European Country in 2018") +
    theme_light()  +
    coord_sf(xlim=c(-40,44), ylim=c(25,70))

```

```{r}

# Find the country with the lowest gap activity rate between woman & men  
mingap2018=min(PC_ActGap$gap) # LT lituania 3.8
PC_ActGap%>%filter(gap==mingap2018)%>%select(CNTR_CODE)


# Find the country with the higher woman activity rate  
maxgap2018=max(PC_ActGap$gap) # Turquey 43%
PC_ActGap%>%filter(gap==maxgap2018)%>%select(CNTR_CODE)


# Find the country with the lowest woman activity  in Europe  
gap2018EU= PC_ActGap %>% 
  filter(! CNTR_CODE %in% c("EA17","EA18","EA19","EU15","EU28","TR","MK","MT"))
max2018UE=max(gap2018EU$gap) #20.6 Italy
gap2018EU%>%filter(gap==max2018UE)%>%select(CNTR_CODE)

# find the country  with the median gap activity rate

gapmoy=median(gap2018EU$gap) #9.5
gap2018EU%>% filter(gap==gapmoy)%>%select(CNTR_CODE) # BE,Belgium

# graph of the evolution of Belgium gap of activity rate 

PC_ActGapTime %>% 
  filter(country=="BE") %>% select(time,gap)%>% ggplot() + geom_line(aes(x=time,y=gap,group=1))+ labs(title="Evolution of Activity gap between woman & men in Belgium") + xlab("time") + ylab("gap of activity rate")


# graph of the evolution of taly  gap of activity rate 
PC_ActGapTime %>% 
  filter(country=="IT") %>% select(time,gap)%>%
  ggplot()+ geom_line(aes(x=time,y=gap,group=1),size=0.5) + labs(title="Evolution of Activity gap between wooman & men in Italy") + xlab("time") + ylab("activity rate")

# graph of the evolution of taly  gap of activity rate 
PC_ActGapTime %>% 
  filter(country=="LT") %>% select(time,gap)%>%
  ggplot()+ geom_line(aes(x=time,y=gap,group=1),size=0.5) + labs(title="Evolution of Activity gap between wooman & men in Lituania") + xlab("time") + ylab("activity rate")



```



```{r}

# How country have the hightest rate of woman that didn't want to find a job
# doc4 = PC_Temp

NowantF=PC_Temp%>%filter(time=="2018" & sex=="F"& reason=="NowantJob")
maxnowant=max(NowantF$values)
NowantF%>%filter(values==maxnowant) # Slovénie 46.5%

```


```{r}
# Evolution of unemployment over the time in EU
PC_UnempUE=PC_Unemp %>% 
  filter(country =="EU28") %>% filter(!sex%in%("T")) %>% group_by(sex)
ggplot(PC_UnempUE) +
   geom_line(aes(x=time,y=PC_unemp,group=sex,colour=sex),size=0.5) + labs(title="Evolution of Unemployent Rate between wooman & men ") + xlab("time") + ylab("Unemployment rate")+ ylim(5,15)+theme(axis.text.x = element_text(angle=45))+geom_vline(xintercept = 9,
                color = "purple", size=1.5) + theme_classic()+theme(axis.text.x = element_text(angle=38))


```




